name: my_pet_shop
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  dio: ^4.0.6
  modal_bottom_sheet: ^2.1.2
  path_provider: ^2.0.11
  json_serializable: ^6.1.3
  flutter_riverpod: ^1.0.4
  equatable: ^2.0.5
  permission_handler: ^9.2.0
  drift: ^1.0.1
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.0
  flutter_secure_storage: ^6.0.0
  card_input_field: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  build_runner: ^2.1.7
  drift_dev: ^1.0.2

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
